[template]
src = "config-local.tmpl"
dest = "/var/www/%%PROJECT%%/config-local.php"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
  "/config/*",
  "/config"
]

reload_cmd = "/usr/sbin/apachectl graceful"
