[template]
src = "idp.tmpl"
dest = "/etc/apache2/mellon/phonebook.idp-metadata.xml"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
    "/identity-provider"
]

reload_cmd = "/usr/sbin/apachectl graceful"
