[template]
src = "okta-idp.tmpl"
dest = "/etc/apache2/mellon/phonebook.idp-metadata.xml"
prefix = "/%%PROJECT%%/%%ENVIRONMENT%%"

keys = [
    "/config-okta"
]

reload_cmd = "/usr/sbin/apachectl graceful"
